### ISSUE TITLE
Nhận xét  của nhóm 18

### ISSUE THREAD

**Issue by tungrg** [cuong091200/DoAnCuoiKy_KHDL#6]
Về tổng thể quy trình làm của các bạn khá là oke
mình chỉ muốn góp ý nho nhỏ là các bạn nên chú thích 1 ít ở chỗ thu thập dữ liệu từ API, có thể giải thích thêm 1 ít về cú pháp hay tại sao lại chọn dữ liệu lấy dữ liệu từ ngày 1/1/2021.

![image](https://user-images.githubusercontent.com/48942478/104600725-f6815700-56ab-11eb-80f3-3fb8515f2fb4.png)

**Comment by cuong091200** [comment]
Bạn hiểu sai ý nhóm mình rồi, nhóm mình lấy dữ liệu đến ngày 1/1/2021

**Comment by cuong091200** [comment]
Hình bạn gửi ý nghĩa gì vậy?

**Comment by tungrg** [comment]
Tại bạn không ghi cách xài API nên mình hiểu nhầm đấy 🐧

**Comment by viplazylmht** [comment]
@tungrg nhóm mình chủ trương dùng API để get hết các trường dữ liệu có sẵn (được gọi là dữ liệu thô, vì chưa hề xử lý gì cả). Sau đó thì nhóm mới khám phá (rất chi tiết) tập dữ liệu thô này, thêm bớt các thuộc tính phù hợp hơn để trả lời cho câu hỏi.

Câu lệnh lấy dữ liệu từ API:
```python
client = Socrata("data.cdc.gov", None)
 
results = client.get("9mfq-cb36", limit=30000)
```
Các dữ liệu này đã được CDC ủy quyền để lưu trữ trên `Socrata`, mà vừa hay `Socrata` lại có thư viện hỗ trợ cho python nên mọi thứ mới đơn giản như vậy 💯  
Sau đó `client` sẽ nhận nhiệm vụ get những dòng dữ liệu có mã `9mfq-cb36` với giới hạn là **30000** dòng. 


Hi vọng câu trả lời của mình giải đáp được thắc mắc của bạn, đồng thời nhóm ghi nhận và sẽ bổ sung phần mô tả này vào bài làm!

**Comment by baocl18ctt2** [comment]
** Ý kiến đóng góp:
Mình thấy đề thấy nhóm bạn chọn rất ý nghĩa, phù hợp với vấn đề thế giới đang đối mặt (tình hình dịch bệnh covid trên tòan thế giới).
Mình xin góp ý về 2 phần đó là phần giải thích và phần tiền xử lý.
Về phần giải thích:  nhóm nên ghi rõ nguồn dữ liệu đó ở đâu.
![image](https://user-images.githubusercontent.com/56357650/104618730-b75d0100-56bf-11eb-9b05-00abffebd6b2.png)
Về phần tiền xử lý:  mình thấy dữ liệu cột này thiếu hơn 50%, nhóm dùng phương pháp mean để điền giá trị thiếu có hợp lý hay không?  
![image](https://user-images.githubusercontent.com/56357650/104618900-dc517400-56bf-11eb-9791-effcb5091df0.png)
- Trên đây là những góp ý của mình.

**Comment by cuong091200** [comment]
> ** Ý kiến đóng góp:
> Mình thấy đề thấy nhóm bạn chọn rất ý nghĩa, phù hợp với vấn đề thế giới đang đối mặt (tình hình dịch bệnh covid trên tòan thế giới).
> Mình xin góp ý về 2 phần đó là phần giải thích và phần tiền xử lý.
> Về phần giải thích: nhóm nên ghi rõ nguồn dữ liệu đó ở đâu.
> ![image](https://user-images.githubusercontent.com/56357650/104618730-b75d0100-56bf-11eb-9b05-00abffebd6b2.png)
> Về phần tiền xử lý: mình thấy dữ liệu cột này thiếu hơn 50%, nhóm dùng phương pháp mean để điền giá trị thiếu có hợp lý hay không?
> ![image](https://user-images.githubusercontent.com/56357650/104618900-dc517400-56bf-11eb-9791-effcb5091df0.png)
> 
> * Trên đây là những góp ý của mình.
